triggers:
  cron: "@weekly"
builders:
  - script
script:
  - "echo \"no op job\""

extra_jobs:
  - name: docker-mongo-5.0
    builders:
      - docker
    docker_name: "library/mongo"
    docker_tags:
      - "5.0"
    docker_context_dir: "5.0"
    docker_skip_tag_as_latest: true
